---
title: "Attack and Damage"
---

### Skill Categories

Combat skills are divided into four categories, depending on the ability they draw upon. Skills from the same or different categories may be combined to create powerful blows.

-	Feats are powerful skills that draw upon strength, causing heavy wounds on the targets.
-	Maneuvers utilize dexterity in order to wear the opponent down.
-	Spells are manifestations of elemental magic, driven by one’s intelligence.
-	Evocations rely on sere willpower to unlock the true potential hidden within.

### Skill Range

Combat skills and weapons have a specific range of effect.

-	Touch: 1m.
-	Close: 2m.
-	Short: 5m.
-	Medium: 10m.
-	Long: 20m.
-	Distant: 50m.

### Damage Type

There are several types of damage, and creatures may be resistant or vulnerable against one or more damage types.

-	Bludgeoning, caused by weapons such as hammers and clubs or certain spells, mainly geomancer ones.
-	Piercing, caused by weapons such as knives and arrows. 
-	Slashing, caused by weapons such as swords and axes or certain spells, mainly aerotheurge ones.
-	Burning, caused by high temperatures, fire, or certain spells, mainly pyrokinetic ones.
-	Frost, caused by low temperatures, ice or certain spells, mainly hydrosophist ones.
-	Radiant, caused by intense light, or certain spells, mainly lightweaver ones.
-	Necrotic, caused by certain weapons or shadowcaster spells.
-	Bleeding, dealt to a creature at the beginning of its turns until it is stopped. 
-	Sunder, caused to objects. Yes, each object has its own Vitality and may as well break.

### Damage & Armor

Armor represents how hard it is to land a solid, damaging blow on a creature. It’s the damage reduction applied on each individual attack. Armor is calculated as the sum of the creature’s the individual armor parts. Some races also receive a natural armor bonus. 

### Ability Contests

Some attacks require a contest between the attacker and the defendant to succeed. These contests are by default deterministic, meaning that the creature with the highest ability score succeeds (ties benefit the defendant). These contests are denoted in parenthesis: the first ability concerns the attacker, and the second the defendant. For example: (strength vs dexterity) or (willpower vs willpower). In many cases, the defendant gets to choose between two ability scores, e.g. (strength vs strength/dexterity). If the attack fails, the special effect (e.g. slowed or enraged) fails as well; all other damage is calculated as normal.

### Turn Example

Ron the human butcher is chasing Grin the goblin for throwing his cat into the stew. The two characters are 14m apart. Ron yields a shovel and a kitchen knife. Grin wears some scraps as armor. The stats of the two creatures are the following:
Ron (level 7): 40 vitality, 20 sanity, 4 strength, 3 dexterity, 2 intelligence, 2 willpower.
Grin (level 3): 30 vitality, 10 sanity, 1 strength, 4 dexterity, 3 intelligence, 1 willpower.

- Both creatures roll d10 for initiative. Ron (8 roll + 3 dex) = 11, Grin (4 roll + 4 dex) = 8.
- Ron starts his turn. He has 4 str, 3 dex, 2 int, 2 will available, plus the 10m of movement.
- Ron moves 10m and utilizes 2 dex to move another 4m and be in touch range of Grin.
-	Ron performs a finesse attack with the dagger (1 dex), enhanced by a fire orb spell (1 int).
-	Ron rolls the damage (6 dagger + 3 fire orb) = 9.
-	Grin has an armor of 1 (scraps), therefore takes (9 – 1) = 8 points of damage. He now has (30 - 8) = 22 vitality points.
-	Ron deals a shovel attack (1 str), enhanced by power attack (1 str) and overpower (1 str). 
- Grin uses the cat reflexes reaction (1 dex) enhanced by evade (2 dex) to move to an adjacent square. 
At this point, Ron still has 1 str, 1 int and 2 will to utilize in his turn. At the end of his turn, all of his ability points will be replenished and ready to use again.Grin has used a reaction (a total of 3 dex points), meaning that in his turn he will only have (4 - 3) = 1 dex point available to utilize. 
